# try:
#     a=5
#     b='0'
#     print (a+b)
# except TypeError:
#     print('Unsupported operation')
# else:
#     print ("Out of try except blocks")  
#####################################################################

# try:
#     f = open("demofile.txt")
#     try:
#         f.write("Lorum Ipsum")
#     except:
#         print("Something went wrong when writing to the file")
#     finally:
#         print('vikash')
#         f.close()
# except:
#     print("Something went wrong when opening the file") 
    
# finally:
#     print('vikash')

###################################################################################
# try:
#   f = open("demofile.txt")
#   try:
#     f.write("Lorum Ipsum")
#   except:
#     print("Something went wrong when writing to the file")
#   finally:
#     f.close()
# except:
#   print("Something went wrong when opening the file")

#########################################################################################
